import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TextBoxComponent } from "@syncfusion/ej2-react-inputs";
import { useState } from "react";

import Box from "@mui/material/Box";
import InputLabel from "@mui/material/InputLabel";
import MenuItem from "@mui/material/MenuItem";
import FormControl from "@mui/material/FormControl";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import { LoadingButton } from "@mui/lab";
import { TextField } from "@mui/material";





const Home: NextPage = () => {
    const [codeInput, setCodeInput] = useState<any>(null);
    const [codeOutput, setCodeOutput] = useState<any>(null);
    const [languageFrom, setLanguageFrom] = useState<any>(null);
    const [languageTo, setLanguageTo] = useState<any>(null);

    const handleChange1 = (event: SelectChangeEvent) => {
        setLanguageFrom(event.target.value as string);
    };

    const handleChange2 = (event: SelectChangeEvent) => {
        setLanguageTo(event.target.value as string);
    };

    const translate = (codeInput: string, languageFrom: string, languageTo: string) => {
        console.log(codeInput);
        console.log(languageFrom);
        console.log(languageTo);

        let translatedCode: string = 'print("Hello World!")';

        setCodeOutput(translatedCode);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>translang</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    translang - the programming language converter
                </h1>
                <Box component="form">
                    <FormControl fullWidth>
                        <InputLabel id="demo-simple-select-label">
                            Language From
                        </InputLabel>
                        <Select
                            labelId="demo-simple-select-label"
                            id="demo-simple-select"
                            value={languageFrom}
                            label="Age"
                            onChange={handleChange1}
                        >
                            <MenuItem value={"Python"}>Python</MenuItem>
                            <MenuItem value={"Java"}>Java</MenuItem>
                            <MenuItem value={"JavaScript"}>JavaScript</MenuItem>
                            <MenuItem value={"C++"}>C++</MenuItem>
                        </Select>
                    </FormControl>

                    <div className="multiline">
                        <TextBoxComponent
                            multiline={true}
                            placeholder="Paste code here (Cmd/Ctrl + V) or enter it manually"
                            onChange={setCodeInput}
                        />
                    </div>
                </Box>
                <Box>
                    <FormControl fullWidth>
                        <InputLabel id="demo-simple-select-label">
                            Language To
                        </InputLabel>
                        <Select
                            labelId="demo-simple-select-label"
                            id="demo-simple-select"
                            value={languageTo}
                            label="Age"
                            onChange={handleChange2}
                        >
                            <MenuItem value={"Python"}>Python</MenuItem>
                            <MenuItem value={"Java"}>Java</MenuItem>
                            <MenuItem value={"JavaScript"}>JavaScript</MenuItem>
                            <MenuItem value={"C++"}>C++</MenuItem>
                        </Select>
                    </FormControl>
                    <TextField
                        id="outlined-multiline-flexible"
                        placeholder="This is where your code will be output"
                        multiline
                        maxRows={Infinity}
                        value={codeOutput}
                    />
                </Box>

                <LoadingButton
                    onClick={() =>
                        // this gets only the codeInput's actual text value, 
                        // which is all I care about for now
                        translate(codeInput.value, languageFrom, languageTo)
                    }
                    style={styles.button}
                >
                    Translate!
                </LoadingButton>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://github.com/Daggerpov/translang"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Code Repository{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/github_logo.png"
                            alt="Github logo"
                            width={64}
                            height={64}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
